/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum29062026;


public class FormMakanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMakanan.class.getName());

   
    
    private FormUtama utama;
    
    public FormMakanan() {
        initComponents();
    }

    public FormMakanan(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ckbNasgor = new javax.swing.JCheckBox();
        ckbMigor = new javax.swing.JCheckBox();
        ckbMire = new javax.swing.JCheckBox();
        txtNasgor = new javax.swing.JTextField();
        txtMigor = new javax.swing.JTextField();
        txtMire = new javax.swing.JTextField();
        cbNasgor = new javax.swing.JComboBox<>();
        cbMigor = new javax.swing.JComboBox<>();
        cbMire = new javax.swing.JComboBox<>();
        txtTotalNasgor = new javax.swing.JTextField();
        txtTotalMigor = new javax.swing.JTextField();
        txtTotalMire = new javax.swing.JTextField();
        txtTotalMakanan = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnHarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PILIHAN MENU MAKANAN");

        ckbNasgor.setText("Nasi Goreng");
        ckbNasgor.addActionListener(this::ckbNasgorActionPerformed);

        ckbMigor.setText("Mie Goreng");
        ckbMigor.addActionListener(this::ckbMigorActionPerformed);

        ckbMire.setText("Mie Rebus");
        ckbMire.addActionListener(this::ckbMireActionPerformed);

        txtNasgor.setText("0");
        txtNasgor.addActionListener(this::txtNasgorActionPerformed);

        txtMigor.setText("0");

        txtMire.setText("0");

        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNasgor.addActionListener(this::cbNasgorActionPerformed);

        cbMigor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMigor.addActionListener(this::cbMigorActionPerformed);

        cbMire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMire.addActionListener(this::cbMireActionPerformed);

        txtTotalNasgor.setText("0");

        txtTotalMigor.setText("0");

        txtTotalMire.setText("0");

        txtTotalMakanan.setText("0");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnHarga.setText("Total Harga");
        btnHarga.addActionListener(this::btnHargaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbMire)
                            .addComponent(ckbMigor)
                            .addComponent(ckbNasgor))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMigor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMire, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbNasgor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMigor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbMire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnHarga))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalMire, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalMigor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnKembali)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbNasgor)
                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMigor)
                    .addComponent(txtMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMire)
                    .addComponent(txtMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>                        

    private void ckbMireActionPerformed(java.awt.event.ActionEvent evt) {                                        
        txtMire.setText("8000");
    }                                       

    private void ckbNasgorActionPerformed(java.awt.event.ActionEvent evt) {                                          
        txtNasgor.setText("15000");
    }                                         

    private void ckbMigorActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txtMigor.setText("10000");
    }                                        

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int jumlah = (int)cbNasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtNasgor.getText());
        double total = jumlah * harga;
        txtTotalNasgor.setText(Double.toString(total));
    }                                        

    private void cbMigorActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int jumlah = (int)cbMigor.getSelectedIndex();
        double harga = Double.parseDouble(txtMigor.getText());
        double total = jumlah * harga;
        txtTotalMigor.setText(Double.toString(total));
    }                                       

    private void cbMireActionPerformed(java.awt.event.ActionEvent evt) {                                       
        int jumlah = (int)cbMire.getSelectedIndex();
        double harga = Double.parseDouble(txtMire.getText());
        double total = jumlah * harga;
        txtTotalMire.setText(Double.toString(total));
    }                                      

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        double a = Double.parseDouble(txtTotalNasgor.getText());
        double b = Double.parseDouble(txtTotalMigor.getText());
        double c = Double.parseDouble(txtTotalMire.getText());
        double total = a+b+c;
        txtTotalMakanan.setText(Double.toString(total));
    }                                        

    private void txtNasgorActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String total = txtTotalMakanan.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMakanan().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbMigor;
    private javax.swing.JComboBox<String> cbMire;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JCheckBox ckbMigor;
    private javax.swing.JCheckBox ckbMire;
    private javax.swing.JCheckBox ckbNasgor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMigor;
    private javax.swing.JTextField txtMire;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtTotalMakanan;
    private javax.swing.JTextField txtTotalMigor;
    private javax.swing.JTextField txtTotalMire;
    private javax.swing.JTextField txtTotalNasgor;
    // End of variables declaration                   
}
